export const jobs = [
  {
    id: 1,
    title: "Executivo de TI - Infraestrutura e Segurança",
    company: "TechParnaíba",
    location: "São Paulo",
    type: "Híbrido",
    salary: "R$ 5.000,00",
  },
  {
    id: 2,
    title: "Pessoa Consultora SAP PS/IM - Sênior",
    company: "Parnaíba Systems",
    location: "Lençóis Paulistas - SP",
    type: "Presencial",
    salary: "R$ 3.200,00",
  },
  {
    id: 3,
    title: "Pessoa Consultora SAP PS/IM - Sênior",
    company: "InovaTech",
    location: "Home Office - Aceitamos Pessoas Canditadas de todo Brasil",
    type: "Remoto",
    salary: "R$ 8.000,00",
  },
  {
    id: 4,
    title: "Pessoa Desenvolvedora Full Stack (React/Next.JS)",
    company: "CodeParnaíba",
    location: "Home Office - Aceitamos Pessoas Canditadas de todo Brasil",
    type: "Híbrido",
    salary: "R$ 4.200,00",
  },
  {
    id: 5,
    title: "Analista Funcional Sênior",
    company: "CodeParnaíba",
    location: "São Paulo ",
    type: "Híbrido",
    salary: "A combinar",
  },
  {
    id: 6,
    title: "Analista de Segurança da Informação",
    company: "CodeParnaíba",
    location: "São Paulo ",
    type: "Híbrido",
    salary: "A combinar",
  },
  {
    id: 7,
    title: "Analista de Governança de TI",
    company: "CodeParnaíba",
    location: "São Paulo ",
    type: "Híbrido",
    salary: "A combinar",
  },
];
